version: '3'

services:
  spring-api-image:
    image: proyecto-hexagonal-1.0.1
    container_name: springh-container2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://bd_mysql:3306/rest_api_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: masterkey
    depends_on:
      bd_mysql:
        condition: service_healthy
  bd_mysql:
    image: mysql:8.0.43
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_PASSWORD: masterkey
      MYSQL_DATABASE: rest_api_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
